### ISSUE TITLE
How to bootstrap new project?

### ISSUE THREAD

**Issue by adamtait** [jdhollis/fenna#1]
This is more of a question. I'm hoping for some advice.

I have followed the steps outlined in [How to Bootstrap Multiple Environments on AWS with Terraform & Fenna](https://theconsultingcto.com/posts/how-to-bootstrap-multiple-environments-on-aws-with-terraform-and-fenna/) (_Thanks for writing that!_).

I noticed that the root account had the root remote state S3 bucket, then the _-tools_ account had all the environment-specific state S3 buckets (_dev-state_, _prod-state_, _stage-state_, _tools-state_).

I went to setup a bootstrap a new service ([a static site](https://github.com/jdhollis/static-site/blob/master/main.tf)).

```
-> fenna bootstrap

What is this service named?
> my-site.com

What's your backend config repository's URL?
> git@github.com/...

Will this service be developed in a sandbox? [yes no]
> no

Which backend would you like to use? [dev root tools]
> dev

Where is your backend stored? [dev root tools]
> dev

What AWS profile would you like to use as your root profile?
> ops
```

However, running init gives me an error:

```
-> fenna init
Initializing modules...
Initializing the backend...
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: ..., host id: ...
```

Looking at the terraform log, I find that access was denied to the _dev-state_ S3 bucket. Terraform has used the _ops-dev_ profile and only the _ops-tools_ profile has access to that bucket.

I tried setting the root profile to _ops-tools_ but same access denied error.

Where have I gone wrong?

**Comment by jdhollis** [comment]
Ah. Perhaps you've encountered a bug in my code. I'll look into it and get back to you soon.

**Comment by jdhollis** [comment]
I think the issue is that the backend for `dev` is in `tools`, not `dev`. Sorry that the language isn't clearer. If you kill the `.fenna` directory and re-run `fenna bootstrap`, change this answer:

```
Where is your backend stored? [dev root tools]
tools
```

**Comment by adamtait** [comment]
Thanks @jdhollis! That worked.

Since the state buckets & locks were created in the tools account, will I always be using `Where is your backend stored?` `> tools`?

**Comment by jdhollis** [comment]
Yep. All of the state management happens in `tools`.

**Comment by jdhollis** [comment]
Oh. I should say that you’ll always be using `tools` except when you need to do something in `root` (which shouldn’t be oftem).

**Comment by adamtait** [comment]
What have you used root for in the past? Maybe a Route 53 zone for an entire business or set of services?

**Comment by jdhollis** [comment]
I've used it for that when it makes sense, but I've tried to push those changes down into the individual environments as much as possible (with different domains per environment). In my ideal environment, `root` sticks to access control for the other environments.
